return {
  ["workshop-1185229307"]={
    configuration_options={
      [""]="",
      DAMAGE_NUMBERS=true,
      DAMAGE_RESISTANCE=true,
      FRAME_PHASES=true,
      HORIZONTAL_OFFSET=0,
      NOEPIC=true,
      NONOEPIC=true,
      WETNESS_METER=false 
    },
    enabled=true 
  },
  ["workshop-1207269058"]={ configuration_options={  }, enabled=true },
  ["workshop-1595631294"]={
    configuration_options={
      BundleItems=false,
      ChangeSkin=true,
      Digornot=false,
      DragonflyChest=false,
      Icebox=false,
      SaltBox=false 
    },
    enabled=true 
  },
  ["workshop-2274329081"]={
    configuration_options={
      ICON_STYLE="new",
      MINIMAP_ICONS=true,
      SHOW_NUMBERS="num_",
      WORLD_COLORS=true,
      WORLD_NUMBERS=true,
      WORMHOLE_BORDER=true,
      WORMHOLE_MARKS_DISABLE=false 
    },
    enabled=true 
  },
  ["workshop-2287303119"]={
    configuration_options={
      [""]=0,
      T_crop=true,
      chestB=-1,
      chestG=-1,
      chestR=-1,
      display_hp=1,
      food_estimation=-1,
      food_order=0,
      food_style=0,
      item_info_mod=0,
      lang="chs",
      show_buddle_item=1,
      show_food_units=-1,
      show_uses=-1 
    },
    enabled=true 
  },
  ["workshop-2505341606"]={
    configuration_options={
      ANNOUNCE_MODE=true,
      CLEANDAYS=15,
      axe=3,
      bee=10,
      beefalo=50,
      birdtrap=10,
      blueprint=3,
      bugnet=3,
      burntground=5,
      clean=true,
      compass=3,
      cutgrass=50,
      deer=10,
      driftwood_log=130,
      earmuffshat=3,
      evergreen_sparse=150,
      feather=2,
      festival=2,
      firehound=10,
      fishingrod=3,
      flies=10,
      flint=50,
      frog=20,
      glommerfuel=10,
      guano=1,
      hammer=3,
      heatrock=10,
      hound=10,
      houndstooth=2,
      lang=true,
      log=50,
      manrabbit_tail=20,
      marsh_tree=100,
      mosquitosack=10,
      nitre=50,
      oceanfishingrod=3,
      pickaxe=3,
      pinecone=50,
      pitchfork=3,
      pocket_scale=3,
      poop=5,
      razor=3,
      rock_petrified_tree=150,
      rocks=50,
      rocky=20,
      rottenegg=2,
      seeds=3,
      shovel=3,
      silk=10,
      skeleton_player=20,
      sketch=1,
      slurtle=5,
      slurtleslime=2,
      spear=3,
      spider=10,
      spiderden=40,
      spidergland=10,
      spoiled_fish=2,
      spoiled_food=2,
      stack=true,
      stack_scanning_range=10,
      stinger=2,
      tacklesketch=1,
      test_mode=false,
      torch=3,
      trap=30,
      twiggytree=150,
      twigs=50,
      winterhat=3 
    },
    enabled=true 
  },
  ["workshop-2577742416"]={
    configuration_options={
      ENABLEPINGS=true,
      FIREOPTIONS=2,
      OVERRIDEMODE=false,
      SHAREMINIMAPPROGRESS=true,
      SHOWFIREICONS=true,
      SHOWPLAYERICONS=true,
      SHOWPLAYERSOPTIONS=2 
    },
    enabled=true 
  },
  ["workshop-2771698903"]={
    configuration_options={
      MOD_RESTART_ALLOW_KILL=true,
      MOD_RESTART_ALLOW_RESTART=true,
      MOD_RESTART_ALLOW_RESURRECT=true,
      MOD_RESTART_CD_BONUS=0,
      MOD_RESTART_CD_KILL=1,
      MOD_RESTART_CD_MAX=0,
      MOD_RESTART_CD_RESTART=2,
      MOD_RESTART_CD_RESURRECT=1,
      MOD_RESTART_FORCE_DROP_MODE=0,
      MOD_RESTART_IGNORING_ADMIN=true,
      MOD_RESTART_MAP_SAVE=1,
      MOD_RESTART_RESURRECT_HEALTH=50,
      MOD_RESTART_TRIGGER_MODE=1,
      MOD_RESTART_WELCOME_TIPS=true,
      MOD_RESTART_WELCOME_TIPS_TIME=10 
    },
    enabled=true 
  },
  ["workshop-374550642"]={ configuration_options={ MAXSTACKSIZE=99 }, enabled=true },
  ["workshop-375850593"]={ configuration_options={  }, enabled=true },
  ["workshop-462372013"]={ configuration_options={  }, enabled=true },
  ["workshop-501385076"]={
    configuration_options={
      quick_cook_on_fire=true,
      quick_harvest=true,
      quick_pick_cactus=true,
      quick_pick_plant_normal_ground=true 
    },
    enabled=true 
  }
  -- ["workshop-841471368"]={
  --   configuration_options={
  --     admin_option=true,
  --     ancient_altar_no_destroy=false,
  --     auto_stack=false,
  --     beefalo_power=false,
  --     cant_destroyby_monster=false,
  --     clean_custom="",
  --     clean_level=-1,
  --     clean_period=10,
  --     connect_worlds=false,
  --     door_lock="000",
  --     eyeturret_player=false,
  --     fence_lock="000",
  --     firesuppressor_dig=30,
  --     give_start_item=true,
  --     house_plain_nodestroy=false,
  --     is_allow_build_near=false,
  --     krampus_sack_ice=false,
  --     language="normal",
  --     minotaur_destroy=false,
  --     minotaur_regenerate=30,
  --     pack_pickup=false,
  --     permission_mode=true,
  --     portal_clear=40,
  --     remove_owner_time="never",
  --     spread_fire=1,
  --     test_mode=false,
  --     trap_teeth_player=false,
  --     wall_hay_lock="000",
  --     wall_moonrock_lock="000",
  --     wall_ruins_lock="000",
  --     wall_stone_lock="000",
  --     wall_wood_lock="000" 
  --   },
  --   enabled=true 
  -- } 
}